# Robot Configuration Parameters
TrajectoryPlannerROS:
    acc_lim_x: 0.1
    acc_lim_th: 0.1
    max_vel_x: 0.2
    min_vel_x: 0.02
    max_vel_theta: 0.2
    min_vel_theta: -0.2
    
    min_in_place_rotational_vel: 0.2
    escape_vel: -0.1
    holonomic_robot: false


    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.1
    yaw_goal_tolerance: 0.1

    # Forward Simulation Parameters
    sim_time: 4
    sim_granularity: 0.025
    vx_samples: 3
    vtheta_samples: 6

    # Trajectory Scoring Parameters
    goal_distance_bias: 0.8
    path_distance_bias: 0.6
    occdist_scale: 0.01
    heading_lookahead: 0.325
    dwa: false

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.01

