map_type: costmap
transform_tolerance: 1.0
obstacle_range: 2.0
raytrace_range: 3.0
inflation_radius: 0.1

footprint: [[0.11,0.15],[0.11,-0.15],[-0.11,-0.15],[-0.11,0.15]]
footprint_padding: 0.1
    

observation_sources: scan

#base_scan_marking: {sensor_frame: base_scan_link,
#                    data_type: PointCloud2,
#                    topic: /base_scan/marking,
#                    expected_update_rate: 0.2,
#                    observation_persistence: 0.0,
#                    marking: true,
#                    clearing: false,
#                    min_obstacle_height: 0.06,
#                    max_obstacle_height: 2.0}

scan: {sensor_frame: hokuyo_link,
            data_type: LaserScan,
            topic: /scan,
            expected_update_rate: 0.5,
            observation_persistence: 0.0,
            marking: true,
            clearing: true,
            min_obstacle_height: -0.10,
            max_obstacle_height: 2.0}

